### ISSUE TITLE
Example Don't work

### ISSUE THREAD

**Issue by mpadronm** [Trakkasure/DataManager#1]
This project is interesting! Example route don't exist. I would like to see the DataManager working before using. I don't understand how it is possible that no one using this powerful tool.

**Comment by Trakkasure** [comment]
First, sorry fro the late response. I have been extremely busy for the past couple of months. Let me review that example and update it.

**Comment by Trakkasure** [comment]
Ok.
All fixed. Lots of rewrite. I restarted 3 projects at once. Took some time to create a private transform for babel.
